### PR TITLE
fixing dashboard integration

### PR DESCRIPTION
**Pull request by sboettcher**
will now work with latest dockerhub dashboard build, which has also been fixed

### CODE REVIEW

**Comment by blootsvoets** [comment]
Nice, thanks for that! Can we also fix the version number of the docker image now that the build is working?

**Comment by sboettcher** [comment]
Do you mean giving the dashboard image a fixed tag instead of `latest`?

**Comment by blootsvoets** [comment]
exactly

**Comment by sboettcher** [comment]
I suppose we could use https://github.com/RADAR-CNS/RADAR-Dashboard/tree/2.0.5-beta-base-href ?
It includes the latest fix. Otherwise @herkulano could make another tagged build?

**Comment by fnobilia** [comment]
Well done. Thank you @sboettcher @herkulano

**Pull request merged**
