### PR TITLE
Update configuration for MP 0.3.0

### PR DESCRIPTION
**Pull request by dennyverbeeck**
Configuration updates for release of ManagementPortal v0.3.0.

[Status of Docker build](https://hub.docker.com/r/radarcns/management-portal/builds/)
[Release notes](https://github.com/RADAR-CNS/ManagementPortal/releases/tag/v0.3.0)

### CODE REVIEW

**Comment by yatharthranjan** [comment]
@dennyverbeeck does this version also have dynamic oauth client registration? Or will that be included in a subsequent release ?

**Comment by nivemaham** [comment]
@yatharthranjan , It doesn't. It will be the next release. So we will have to drop the database again

**Comment by yatharthranjan** [comment]
@nivemaham Okay thanks.

**Comment by nivemaham** [comment]
@yatharthranjan Please hold on this this merge. We are testing the new release and we may need to update the release.

**Pull request merged**
