### PR TITLE
Release-1.0.0

### PR DESCRIPTION
**Pull request by nivemaham**
Bringing the current stack to the master for release 1.0.0 of the platform

### CODE REVIEW

**Comment by blootsvoets** [comment]
Looks good, still waiting for #87 though. `keystore.jks` should be removed and added to `etc/.gitignore`.

**Comment by yatharthranjan** [comment]
Yes nivethika. Please hold off on this till #87 is merged. Sorry got a little occupied here with the recruitment but will do it by tomorrow.

**Comment by yatharthranjan** [comment]
Can we add the latest version of RADAR-Scemas (to radar kafka init) and RADAR-Backend to the images and docker-compose please

**Comment by yatharthranjan** [comment]
I think we are ready for this release now. Or should we hold off on this till a new version of the Rest API is released ? What do you guys think @nivemaham @blootsvoets

**Comment by nivemaham** [comment]
The reason i initiated this release was to tag the version that we were using on production for the studies started in November. But that is not the case anymore. I think we can release it now. The new rest-api version may take a while with all the expected changes. We can do another release when it is ready.

**Comment by yatharthranjan** [comment]
I have rebased this branch with dev to incorporate all the latest updates.

**Comment by yatharthranjan** [comment]
@nivemaham I think we can merge now. The latest working branch is the dev branch. When we make the release we should ensure that the version of each component of the stack is enlisted.

**Pull request merged**
