### PR TITLE
Out of memory fix

### PR DESCRIPTION
**Pull request by blootsvoets**
Fixes ADAR-CNS/RADAR-HDFS-Sink-Connector#4.

### CODE REVIEW

**Comment by sboettcher** [comment]
Since we are at it, would you agree to also set the default maximum log retention time to one month instead of one week? Or at least specifying it in the docker-compose so that configurations can easily be changed depending on the environment.
```diff
diff --git a/dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml b/dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
index d52a1f1..054e5aa 100644
--- a/dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
+++ b/dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
@@ -71,6 +71,7 @@ services:
       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
+      KAFKA_LOG_RETENTION_HOURS: 730
 
   kafka-2:
     image: confluentinc/cp-kafka:3.1.2-1
@@ -87,6 +88,7 @@ services:
       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
+      KAFKA_LOG_RETENTION_HOURS: 730
 
   kafka-3:
     image: confluentinc/cp-kafka:3.1.2-1
@@ -103,6 +105,7 @@ services:
       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
+      KAFKA_LOG_RETENTION_HOURS: 730
 
   #---------------------------------------------------------------------------#
   # Schema Registry                                                           #
```

**Comment by blootsvoets** [comment]
Added. @sboettcher would you please review this?

**Comment by sboettcher** [comment]
FYI this is one month not one week.

**Comment by blootsvoets** [comment]
Ok good to know. This will increase the size of the Kafka volumes a lot, but it's also possible to temporarily set a lower threshold to reduce the size.

**Pull request merged**
